### ISSUE TITLE
SvgNet produces invalid decimal seperator in German culture

### ISSUE THREAD

**Issue by housemysedar** [managed-commons/SvgNet#1]
SvgNet generates the comma "," instead of the dot "." if used in German culture. E.g. Inkscape won't understand this and show misplaced elements.

The fix is quite simple:
In Types.cs, line 232

replace
string s = _num.ToString();

with
string s = _num.ToString(System.Globalization.CultureInfo.InvariantCulture);

This should work for any country.

**Comment by oli-arborum** [comment]
1. A missing culture parameter was found in `SvgTypes.SvgPath.ToString()` where `d.ForString()` for a float variable is called.

2. Regarding the hashtables that may contain `float`s I propose the following code for the first foreach loop in `SvgElement.WriteXmlElements()`:

                if (_atts[s] is float)
                {
                    me.SetAttribute(s, doc.NamespaceURI, ((float)_atts[s]).ToString(System.Globalization.CultureInfo.InvariantCulture));
                }
                else if (_atts[s] is double)
                {
                    me.SetAttribute(s, doc.NamespaceURI, ((double)_atts[s]).ToString(System.Globalization.CultureInfo.InvariantCulture));
                }
                else
                {
                    me.SetAttribute(s, doc.NamespaceURI, _atts[s].ToString());
                }

**Comment by monoman** [comment]
Published new nuget with last fixes: https://www.nuget.org/packages/SvgNet/1.0.1
