### ISSUE TITLE
Locale affects SVG rendering

### ISSUE THREAD

**Issue by runegri** [managed-commons/SvgNet#12]
When running my application in Norwegian locale ("nb-NO") decimal numbers are written using a comma instead of a period (, instead of .). This breaks the rendered SVG file if you are using pens where the thickness is a decimal number (say 1.5) since it is rendered as 1,5 instead of 1.5. 

Steps to reproduce:
Run your application in Norwegian locale. Draw a line using a pen with thickness 0.5. See that the stroke-width of the pen is outputted as 0,5 instead of 0.5. 

Workaround:
Change the CurrentCulture of your application to en-US when rendering the SVG. The following works fine: `Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");`

**Comment by monoman** [comment]
I'll take a look.

**Comment by monoman** [comment]
Fixed where I could find. Released as 1.0.5  https://www.nuget.org/packages/SvgNet/1.0.5
