### ISSUE TITLE
Save / restore transformations??

### ISSUE THREAD

**Issue by i00** [managed-commons/SvgNet#13]
Hi ... just a suggestion

I think that saving /restoring states shouldn't be that hard to do as surely you would just have to prod around the _transforms matrix??

.. you would not even need to store the information in the GraphicsState itself (since it is not inheritable) :P ... you could create one with any graphics object specifically for this purpose (since it has no public constructor) and just store a dictionary of GraphicsStates against the matrix at the time .Save was called.. then when restore is called load back the matrix that matches the state.

Kris

**Comment by monoman** [comment]
Thanks Kris, for the ideas, but I can't delve into SvgNet now to learn what
you are talking about 🤔.
Care to send a Pull Request? I would review and merge it as soon as
possible.

Rafael Teixeira
O..:.)oooo

**Comment by i00** [comment]
I just looked into it.. haven't actually made any changes.
Kris

**Comment by monoman** [comment]
No details provided in months - timed out
