### ISSUE TITLE
DrawImage StackOverflow exception

### ISSUE THREAD

**Issue by Keex0r** [managed-commons/SvgNet#14]
Hello,
one of the DrawImage overloads in SVGGraphics.cs is causing a StackOverflow exception:

The culprit is (line 1656):

        /// <summary>
        /// Implemented
        /// </summary>
        public void DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
        {
            DrawImage(image, x, y, width, height);
        }

It misses type conversion of the parameter and hence calls itself recursively. A fix would be to add the typecasting to call the correct base overload:

        /// <summary>
        /// Implemented
        /// </summary>
        public void DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
        {
            DrawImage(image, (Single)x, (Single)y, (Single)width, (Single)height);
        }

Best regards
Jens

**Comment by monoman** [comment]
Thanks for the report @Keex0r

**Comment by monoman** [comment]
Published nuget 1.0.6 with this fix : https://www.nuget.org/packages/SvgNet/1.0.6
