### ISSUE TITLE
Implicit lineto commands are not parsed correctly

### ISSUE THREAD

**Issue by glopesdev** [managed-commons/SvgNet#16]
I was trying to validate some SVG documents, and suddenly noticed that the parser does not correctly handle implicit **lineto** commands. For example, the following path definition should draw two disconnected lines as part of the same path:

```xml
<path d="m 2.5260284,293.65894 0.8048868,-1.79707 m 1.6705196,-0.15693 0.784638,1.84769"/>
```

According to the [SVG specification](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands): "If a moveto is followed by multiple pairs of coordinates, the subsequent pairs are treated as implicit lineto commands. Hence, implicit lineto commands will be relative if the moveto is relative, and absolute if the moveto is absolute."

However, the SvgPath class parser appears to treat this as a single line. Because of this, it is impossible to parse many of the more complex paths generated by software such as inkscape. I understand SvgNet had a bigger focus in writing SVG, but reading SVG is useful as well, to allow serialization of GDI+ commands, for example in copy/paste functions or storing/retrieving line drawings.

**Comment by monoman** [comment]
Thanks, I'll take a look

Rafael Teixeira
O..:.)oooo
