### ISSUE TITLE
Transforms ignored in DrawLines method

### ISSUE THREAD

**Issue by Keex0r** [managed-commons/SvgNet#17]
Hello,
I noticed that GDI transformations (in my case a Translation) were ignored in the DrawLines method.

The culprit was line 1846 of SVGGraphics.cs:
old: `pl.Transform = new SvgTransformList(_transforms.Top.Clone());`
fix: `pl.Transform = new SvgTransformList(_transforms.Result.Clone());`

It would be nice if you could check if the fix is correct. I basically just adjusted it to be the same as Transformation handling in other methods.

Cheers
Jens

**Comment by monoman** [comment]
Fixed on version 1.0.8 released to Nuget
