### ISSUE TITLE
Net Standard version

### ISSUE THREAD

**Issue by vpenades** [managed-commons/SvgNet#19]
Could it be possible to upgrade SvgNet to NetStandard/NetCore?

Thanks!

**Comment by monoman** [comment]
Let's put it in the queue. Contributions are welcome!!! 🥇

**Comment by monoman** [comment]
PR reviewed and tweaked and merge, and compiling as .NET Standard 2.0, but I was not able to make it run under .NET Core 😢

**Comment by vpenades** [comment]
@monoman I've tried your NetCore project;  lower the NetCore version from 2.2 to 2.0 and it will work just fine.

Also, I would suggest to move your test projects to proper NUnit tests now that you can run NetCore 2.0
