### ISSUE TITLE
Clarify and unify the license header in source files

### ISSUE THREAD

**Issue by xmojmr** [managed-commons/SvgNet#3]
The final goal of this ticket is to make clear who is the new license holder and what GitHub user's can do with it and make sure that exactly same copy of the license is present in the source files.

Original code publisher ([Ben Peterson, 9 Mar 2003](http://www.codeproject.com/Articles/3751/An-SVG-framework-in-C-and-an-SVG-GDI-bridge)) does not maintain the code anymore so the license agreement should be reconnected to _here_.

I tried to find the correct solution myself by reading answers to a few licensing questions like [http://programmers.stackexchange.com/search?q=relicense bsd](http://programmers.stackexchange.com/search?page=1&tab=relevance&q=relicense%20bsd) but failed.

This is not permissive `WTFPL` and the original copyright owner ([Riskcare](http://www.riskcare.com/about/about-overview)) legally exists so I don't know how to resolve it with a pull request as I'm not a lawyer.

From my point of view the correct way out is to contact [Benjamin Peterson](https://www.linkedin.com/pub/benjamin-peterson/a/b96/a48), even though he does not work for Riskcare anymore, and negotiate with him the copyright change.

Some related things I find strange:

1. license present in source files looks like [BSD-2-Clause](http://opensource.org/licenses/BSD-2-Clause) but instead of BSD text "SOFTWARE IS PROVIDED BY THE **COPYRIGHT HOLDERS** AND CONTRIBUTORS" the license contains "SOFTWARE IS PROVIDED BY THE **AUTHOR** AND CONTRIBUTORS". Author and copyright holder may be different things
2. license present in `readme` looks like [BSD-3-Clause](http://opensource.org/licenses/BSD-3-Clause) but instead of BSD text "SOFTWARE IS PROVIDED BY THE **COPYRIGHT HOLDERS** AND CONTRIBUTORS" the license contains "SOFTWARE IS PROVIDED BY THE **AUTHOR**". The  contributors part is missing and author and copyright holder may be different things
3. license present in `readme` adds `Copyright © 2010 SvgNet & SvgGdi Bridge Project. All rights reserved` clause. 
4. license in some new edited files adds `Copyright © 2010 SvgNet & SvgGdi Bridge Project. All rights reserved` clause
5. license in the old source files does not mention `Copyright © 2010 SvgNet & SvgGdi Bridge Project` at all
6. original `CodeProject` license said: "_SvgNet is an Open Source project under a BSD-like license (license terms are reproduced in every SvgNet source file). SvgNet is copyright 2003 **RiskCare** Ltd._". The company "RiskCare Ltd." with exactly this name may be already gone and the new company "Riskcare" might loose it's rights or the company may not even know or care about some source code created by it's ex-employees decade ago

**Comment by bjsp123** [comment]
I'm the original author -- thanks for your interest in SvgNet.  I wrote SvgNet more than 10 years ago at Riskcare Ltd -- the copyright holder is therefore Riskcare.  Riskcare still exists (www.riskcare.com), though I doubt if anyone there remembers this code.

As for the wording in the license, I'm afraid I have no idea where it comes from!  The intention was for it to be a BSD-2 style license, so treating it thus would be in the spirit of the original project. 

I would suggest contacting Riskcare's current CTO, if you need details from Riskcare -- although he wasn't there when this code was written.  In fact, I'll send him a note now...

**Comment by monoman** [comment]
Thanks for the clarification, so far!

Rafael Teixeira
O..:.)oooo
