### ISSUE TITLE
Include net5.0-windows target

### ISSUE THREAD

**Issue by glopesdev** [managed-commons/SvgNet#40]
For an improved build experience on projects migrating WinForms applications to .NET 5.0 it would be great to include a new target framework for `net5.0-windows` which bypasses the need for `System.Drawing.Common` altogether. This is the official equivalent of the old .NET framework windows forms, for projects targeting the windows platform.

The change is quite simple, I will add a pull request shortly to demonstrate it and also include conditional removal of `System.Drawing.Common` for targets which do not require it.

**Comment by monoman** [comment]
Thanks, I've made TargetFrameworks conditionally include net461 and net5.0-windows only when building in Windows, which is the case when I generate the package to publish on Nuget, so the official package has all 5 versions of the dll, while building in ubuntu as done in the GitHub actions it only compiles for netstandard2.0, netstandard2.1 and net5.0.

**Comment by glopesdev** [comment]
Thanks @monoman that's great. I noticed that the NuGet packages seem to be published only on GitHub now? Looking at the NuGet gallery link it seems the latest version is 2.1.1: https://www.nuget.org/packages/SvgNet

Is there an alternate repository we should use to target the library in other Visual Studio projects?

**Comment by monoman** [comment]
I've not automated publishing to Nuget Gallery, yet. I will do it manually
once more.

Rafael Teixeira
O..:.)oooo

**Comment by monoman** [comment]
Version 2.1.6 published and listed: https://www.nuget.org/packages/SvgNet

Rafael Teixeira
O..:.)oooo
