### ISSUE TITLE
SvgTextElement constructor shouldn't accept floats.

### ISSUE THREAD

**Issue by MartinJSoles** [managed-commons/SvgNet#52]
There is a constructor for the SvgTextElement that accepts the text and two floats. These floats are being implicitly converted to SvgLength objects with an unknown length type.

This overload should be deprecated and a new one added that accepts x and y as SvgLength objects. This would remove any ambiguity in what the values truly mean.

**Comment by MartinJSoles** [comment]
I created a pull request, #53, to add a constructor overload and mark the one that accepts floats as obsolete.

**Comment by monoman** [comment]
Merged the PR - Thanks
