### ISSUE TITLE
Add net472 target

### ISSUE THREAD

**Issue by glopesdev** [managed-commons/SvgNet#58]
The new 3.0.0 release of SvgNet introduces a new dependency to `System.ValueTuple` package for .NET framework platform 4.6.1.

If indeed `ValueTuple` is a requirement now, would it be possible to bump the plaftorm target version to .NET 4.7.2 without that extra dependency? Or alternatively add a new platform target for .NET 4.7.2? It would be great to have a release of the package for framework without any extra dependencies.

**Comment by glopesdev** [comment]
It turns out that `System.ValueTuple` was really only used in a very small number of cases, so I've opened a PR to just rework those call sites to avoid pulling in the extra dependency, as it seemed worth it to change very few lines and be able to target seamlessly a broader range of platforms.

**Comment by monoman** [comment]
Ok I'll look into your PR
