### ISSUE TITLE
System.Drawing.Common should be dropped for net8.0-windows

### ISSUE THREAD

**Issue by glopesdev** [managed-commons/SvgNet#78]
The latest version of [`SvgNet`](https://www.nuget.org/packages/SvgNet#dependencies-body-tab) takes up an extra dependency to `System.Drawing.Common` when targeting `net8.0-windows`.

This is strange since the project configuration seems to be correctly declared but maybe something was lost in the deployment process. It's not there for the other related frameworks, e.g. `net6.0-windows` and `net7.0-windows` correctly drop the dependency.

**Comment by monoman** [comment]
With some other cleanups for dropping support for .net 7.0 (EOL) released version 3.3.8 in nuget.org
